src/main/java/com/devonoff/DevOnOffApplication.java
src/main/java/com/devonoff/config/SecurityConfig.java
src/main/java/com/devonoff/controller/AuthController.java
src/main/java/com/devonoff/entity/User.java
src/main/java/com/devonoff/service/UserServiceImpl.java
src/main/java/com/devonoff/user/controller/AuthController.java
src/main/java/com/devonoff/user/dto/SignUpRequest.java
src/main/java/com/devonoff/user/entity/User.java
src/main/java/com/devonoff/user/repository/UserRepository.java
src/main/java/com/devonoff/user/service/UserService.java
src/main/java/com/devonoff/user/service/UserServiceImpl.java
src/main/java/com/devonoff/user/type/LoginType.java

> ### 변경사항
> sign-up  기능추가
> 📌 **AS-IS**
>   회원가입기능 X
> 🔖 **TO-BE**
>   회원가입기능 O 
> ### 테스트
> - [ ] 테스트 코드
> - [X] API 테스트 

feat: sign-up 기능추가

---

.gitignore
build.gradle
src/main/java/com/devonoff/domain/studyPost/entity/StudyPost.java
src/main/resources/application.yml

> ### 변경사항
> 
> 📌 **AS-IS**
- 코드 병합 중 StudyPostMapper에서 Request 필드를 찾지 못하는 문제 발생
> 🔖 **TO-BE**
- build.gradle에 lombok 의존성 위에 위치한 mapstruct 의존성을 lombok 아래로 위치시켜 문제 해결 
> ### 테스트
>
> - [x] 테스트 코드

fix: mapstruct 의존성 문제 해결

---

build.gradle

> ### 변경사항
> 🔖 **TO-BE**
> - 의존성 중복 및 순서로인한 실행 에러 해결
> ### 테스트
>
> - [ ] 테스트 코드

fix: 의존성 중복 에러

---

src/main/java/com/devonoff/exception/GlobalExceptionHandler.java

> ### 변경사항
> 
> 📌 **AS-IS**
> GlobalExceptionHandler가 모든 예외에 상태코드 200을 내려줌
> 🔖 **TO-BE**
> GlobalExceptionHandler가 각각 예외에 맞는 상태코드를 내려줌
> ### 테스트
>
> - [X] API 테스트: 포스트맨으로 정상작동하는 것을 확인

 fix: 상태코드 200만 내려주던 errorHandler를 각 예외에 맞는 상태코드를 내려주도록 변경

---

src/main/java/com/devonoff/domain/student/dto/StudentDto.java
src/main/java/com/devonoff/domain/student/repository/StudentRepository.java
src/main/java/com/devonoff/domain/study/controller/StudyController.java
src/main/java/com/devonoff/domain/study/service/StudyService.java

> ### 변경사항
> 
> 📌 **AS-IS**
> 🔖 **TO-BE**
- 스터디 참가자 리스트 조회 기능 구현
> ### 테스트
>
> - [ ] 테스트 코드

feat: 스터디 참가자 리스트 조회 기능 구현

---

src/main/java/com/devonoff/domain/photo/service/PhotoService.java
src/main/java/com/devonoff/domain/user/controller/UserController.java
src/main/java/com/devonoff/domain/user/dto/UserUpdateRequest.java
src/main/java/com/devonoff/domain/user/dto/auth/SignUpRequest.java
src/main/java/com/devonoff/domain/user/service/AuthService.java
src/main/java/com/devonoff/domain/user/service/UserService.java
src/main/java/com/devonoff/type/ErrorCode.java
src/main/resources/application.yml
src/test/java/com/devonoff/domain/user/controller/AuthControllerTest.java
src/test/java/com/devonoff/domain/user/controller/UserControllerTest.java
src/test/java/com/devonoff/domain/user/service/AuthServiceTest.java
src/test/java/com/devonoff/domain/user/service/UserServiceTest.java

> ### 변경사항
>
> 📌 **AS-IS**
>  - 소셜 로그인 기능 구현 및 테스트 코드 작성
> 🔖 **TO-BE**
> - 유저 정보 조회, 수정 및 프로필 이미지 관리 기능 추가
>
>	- 유저 정보 조회, 수정 기능 구현
>	- 프로필 이미지 수정 및 삭제 기능 구현
>	- 프로필 이미지 삭제 시 profileImageUrl 필드를 null로 설정하여 이미지가 없는 상태로 처리
>
> - 테스트 코드 작성
>
>	- 유저 정보 조회, 수정, 프로필 이미지 수정 및 삭제 관련 테스트 코드 작성
>	- 회원 탈퇴 시, 탈퇴 회원과 관련된 스터디에서 해당 회원을 제거하는 로직 테스트 코드 작성
>
> - ErrorCode 추가
>
>	- 로그인된 사용자와 요청한 사용자가 다를경우의 ErrorCode 추가 및 적용
>
> - 리팩토링
>
>	- 사용하지 않는 import 정리
> ### 테스트
>
> - [x] 테스트 코드

유저 정보 상세 조회 및 수정, 프로필 이미지 수정 및 삭제 기능 구현

---

src/main/java/com/devonoff/domain/infosharepost/controller/InfoSharePostController.java
src/main/java/com/devonoff/domain/infosharepost/service/InfoSharePostService.java
src/main/java/com/devonoff/domain/qnapost/controller/QnaPostController.java
src/main/java/com/devonoff/domain/qnapost/service/QnaPostService.java
src/main/java/com/devonoff/domain/study/controller/StudyController.java
src/main/java/com/devonoff/domain/study/service/StudyService.java
src/main/resources/application.yml
src/test/java/com/devonoff/domain/comment/service/CommentServiceTest.java
src/test/java/com/devonoff/domain/qnapost/service/QnaPostServiceTest.java
src/test/java/com/devonoff/domain/study/controller/StudyControllerTest.java
src/test/java/com/devonoff/domain/study/service/StudyServiceTest.java
src/test/java/com/devonoff/infosharepost/controller/InfoSharePostControllerTest.java

> ### 변경사항
> 📌 **AS-IS**
> 🔖 **TO-BE**
- 스터디 생성 성공
- 실패: 모집글 없음
- 본인이 속한 스터디 목록 조회 성공
- 스터디 참가자 목록 조회 성공
> ### 테스트
>
> - [x] 테스트 코드

스터디 관련 기능(성공/실패 케이스) 테스트 코드 작성

---

src/test/java/com/devonoff/domain/student/service/StudentServiceTest.java

> ### 변경사항
> 📌 **AS-IS**
> 🔖 **TO-BE**
- 스터디에서 특정 참가자 삭제 성공
- 스터디에서 특정 참가자 삭제 실패 - 유저 없음
> ### 테스트
>
> - [x] 테스트 코드

스터디 참가자 관련 기능(성공/실패 케이스) 테스트 코드 작성

---

src/main/java/com/devonoff/config/BatchConfig.java
src/main/java/com/devonoff/domain/user/entity/User.java

> ### 변경사항
> 📌 **AS-IS**
> 🔖 **TO-BE**
- User 삭제 시 관련 StudyPost 자동 삭제를 위해 CascadeType.REMOVE 추가
- User와 StudyPost 간 연관관계 처리 개선
> ### 테스트
>
> - [ ] 테스트 코드

feat: User 엔티티에 StudyPost 연관관계 Cascade 설정 추가

---

src/main/resources/application.yml

> ### 변경사항
> 📌 **AS-IS**
> 🔖 **TO-BE**
- 배치 JDBC 스키마 초기화 설정 수정
> ### 테스트
>
> - [ ] 테스트 코드

fix: 배치 JDBC 스키마 초기화 설정 수정

---

src/test/java/com/devonoff/domain/user/controller/AuthControllerTest.java
src/test/java/com/devonoff/domain/user/controller/UserControllerTest.java
src/test/java/com/devonoff/domain/user/service/UserServiceTest.java

> ### 변경사항
> 
> 📌 **AS-IS**
>
> 🔖 **TO-BE**
> - 프로필 이미지 삭제, 수정시 ModelAttribute -> RequestParam 으로 이미지 파일 받는 방식 변경으로 인한 테스트 코드 변경
> - 프로필 이미지 삭제시 프로필 이미지 null -> 프로필 이미지를 기본 이미지로 변경 로직에 따른 테스트 코드 변경
> - 회원 가입시 비밀번호 패턴 확인으로 인해 테스트 코드 변경
> ### 테스트
>
> - [x] 테스트 코드

fix: 코드 변경으로 인한 테스트 코드 수정

---

build.gradle
src/main/java/com/devonoff/config/WebSocketConfiguration.java
src/main/java/com/devonoff/domain/faceCall/controller/HealthCheckController.java
src/main/java/com/devonoff/domain/faceCall/controller/SignalingController.java
src/main/java/com/devonoff/domain/faceCall/util/RoomManager.java
src/main/java/com/devonoff/domain/faceCall/util/StudyIdSessionManager.java
src/main/java/com/devonoff/domain/faceCall/util/TimeManager.java
src/main/java/com/devonoff/domain/faceCall/util/UserIdSessionManager.java
src/main/java/com/devonoff/domain/faceCall/util/WebSocketEventListener.java

> ### 변경사항
> 
> 📌 **AS-IS**
> 🔖 **TO-BE**
> 화상채팅 기능 추가
> 스터디 타임라인 연동
> ### 테스트
>

feat: 화상채팅 기능 추가, 스터디 타임라인 연동

---

src/main/java/com/devonoff/domain/infosharepost/controller/InfoSharePostController.java
src/main/java/com/devonoff/domain/infosharepost/service/InfoSharePostService.java
src/test/java/com/devonoff/infosharepost/controller/InfoSharePostControllerTest.java

> ### 변경사항
> 
> 📌 **AS-IS**
> 🔖 **TO-BE**
> 정보 공유 게시판 페이지 사이즈 10 -> 12로 통일
> ### 테스트
>
> - [X] 테스트 코드

fix: 전체 통일을 위해 정보공유 게시판 page 크기를 12로 변경

---

src/main/java/com/devonoff/config/SecurityConfig.java

> ### 변경사항
> 
> 📌 **AS-IS**
> 🔖 **TO-BE**
> 권한이 필요없는 게시글, 댓글 조회시 접속 허용
> ### 테스트
>

fix: 권한이 필요없는 게시글, 댓글 조회시 접속 허용

---

src/main/java/com/devonoff/domain/infosharepost/controller/InfoSharePostController.java
src/main/java/com/devonoff/domain/infosharepost/dto/InfoSharePostDto.java
src/main/java/com/devonoff/domain/infosharepost/service/InfoSharePostService.java
src/main/java/com/devonoff/domain/photo/service/PhotoService.java
src/main/java/com/devonoff/domain/qnapost/controller/QnaPostController.java
src/main/java/com/devonoff/domain/qnapost/dto/QnaPostDto.java
src/main/java/com/devonoff/domain/qnapost/dto/QnaPostRequest.java
src/main/java/com/devonoff/domain/qnapost/dto/QnaPostUpdateDto.java
src/main/java/com/devonoff/domain/qnapost/service/QnaPostService.java
src/main/java/com/devonoff/domain/studyPost/controller/StudyPostController.java
src/main/java/com/devonoff/domain/studyPost/dto/StudyPostCreateRequest.java
src/main/java/com/devonoff/domain/studyPost/dto/StudyPostUpdateRequest.java
src/main/java/com/devonoff/domain/studyPost/entity/StudyPost.java
src/main/java/com/devonoff/domain/studyPost/service/StudyPostService.java

> ### 변경사항
> 
> 📌 **AS-IS**
> 🔖 **TO-BE**
> 기본 썸네일, 기본 프로필 삭제 불가로 변경
> 게시글 생성,수정 방식 통일
> ### 테스트
>

fix: 기본 썸네일 관련 게시판 생성,수정,삭제 변경

---

src/test/java/com/devonoff/domain/infosharepost/controller/InfoSharePostControllerTest.java
src/test/java/com/devonoff/domain/infosharepost/service/InfoSharePostServiceTest.java
src/test/java/com/devonoff/domain/qnapost/controller/QnaPostControllerTest.java
src/test/java/com/devonoff/domain/qnapost/service/QnaPostServiceTest.java
src/test/java/com/devonoff/domain/studyPost/controller/StudyPostControllerTest.java
src/test/java/com/devonoff/domain/studyPost/service/StudyPostServiceTest.java

> ### 변경사항
> 🔖 **TO-BE**
> - 정보공유 게시글 댓글, 대댓글 테스트 코드 작성
> - 질의응답 게시글 댓글, 대댓글 테스트 코드 작성
> - 스터디 모집 게시글 댓글, 대댓글 테스트 코드 작성
> ### 테스트
>
> - [x] 테스트 코드

댓글, 대댓글 분리해 로직변경에 대한 테스트 코드 작성 

---

src/main/java/com/devonoff/common/entity/BaseTimeEntity.java
src/main/java/com/devonoff/config/BatchConfig.java
src/main/java/com/devonoff/domain/studyPost/repository/StudyPostRepository.java
src/test/java/com/devonoff/config/BatchConfigTest.java

> ### 변경사항
> 📌 **AS-IS**
> 🔖 **TO-BE**
- 스터디 모집글 자동 삭제 배치 작업에 댓글 및 대댓글 삭제 기능 추가
> ### 테스트
>
> - [x] 테스트 코드

feat: 스터디 모집글 자동 삭제 배치 작업에 댓글 및 대댓글 삭제 기능 추가

---

src/main/java/com/devonoff/domain/studyPost/repository/StudyPostRepository.java
src/main/java/com/devonoff/domain/studyPost/service/StudyPostService.java
src/test/java/com/devonoff/domain/studyPost/service/StudyPostServiceTest.java

> ### 변경사항
> 📌 **AS-IS**
- 스터디 모집글 유저id 기반 상세조회 시 오래된순 정렬 데이터 노출
> 🔖 **TO-BE**
- 스터디 모집글 상세조회(userId) 최신순 정렬 기능 추가
> ### 테스트
>
> - [x] 테스트 코드

feat: 스터디 모집글 상세조회(userId) 최신순 정렬 기능 추가

---

src/main/java/com/devonoff/domain/qnapost/dto/QnaPostDto.java
src/main/java/com/devonoff/domain/qnapost/repository/QnaPostRepository.java
src/main/java/com/devonoff/domain/qnapost/service/QnaPostService.java
src/test/java/com/devonoff/domain/qnapost/service/QnaPostServiceTest.java

> ### 변경사항
>
> 🔖 **TO-BE**
> - Qna 게시글 생성일자, 수정일자 응답
> - Qna 게시글 최신순으로 정렬
> - 수정된 코드에 대한 테스트 코드 작성
> ### 테스트
>
> - [x] 테스트 코드

질의응답 게시글 생성일자, 수정일자 응답 및 최신순 정렬

---

src/main/java/com/devonoff/domain/user/service/AuthService.java
src/test/java/com/devonoff/domain/user/service/AuthServiceTest.java

> ### 변경사항
> 
> 🔖 **TO-BE**
> -  회원 탈퇴 진행후 탈퇴한 회원 표시할 경우 닉네임을 "탈퇴한 유저" -> "탈퇴한 회원" 으로 변경
> ### 테스트
>
> - [x] 테스트 코드

탈퇴한 회원 표시할 경우 닉네임을 "탈퇴한 유저" -> "탈퇴한 회원" 으로 변경

---

src/main/java/com/devonoff/domain/study/dto/StudyDto.java
src/main/java/com/devonoff/domain/user/service/AuthService.java
src/test/java/com/devonoff/domain/user/service/AuthServiceTest.java

> ### 변경사항
> 
> 🔖 **TO-BE**
> - 회월탈퇴시 탈퇴한 회원의 닉네임 설정을 "탈퇴한 유저" -> "탈퇴한 회원" 으로 변경
> ### 테스트
>
> - [x] 테스트 코드

Develop 수정사항 Main 으로 머지

---

src/main/java/com/devonoff/domain/user/service/social/SocialAuthService.java
src/test/java/com/devonoff/domain/user/service/social/SocialAuthServiceTest.java

> ### 변경사항
>
> 🔖 **TO-BE**
> - 소셜 로그인 사용자 엑세스 토큰 재발급 안되던 버그 수정 및 코드 변경에 대한 테스트 코드 작성
> ### 테스트
>
> - [x] 테스트 코드

소셜 로그인 사용자 엑세스 토큰 재발급 안되던 버그 수정

---

src/test/java/com/devonoff/config/BatchConfigTest.java

> ### 변경사항
> 
> 📌 **AS-IS**
- BatchConfigTest에서 StudyCommentRepository와 StudyReplyRepository에 대한 Mock 설정 및 검증이 포함되어 있었음
> 🔖 **TO-BE**
- 이전 배치관련 작업에서 StudyComment 및 StudyReply 엔티티에 CascadeType.REMOVE 를 추가하고, BatchConfig에서 불필요한 댓글/대댓글 삭제 코드 제거에 따라 BatchConfigTest 댓글 및 대댓글 삭제와 관련된 Mock 설정 및 검증을 제거
> ### 테스트
>
> - [x] 테스트 코드

test: BatchConfigTest 로직 수정 및 간소화

---

src/main/java/com/devonoff/domain/photo/service/PhotoService.java

> ### 변경사항
> 
> 📌 **AS-IS**
> photoService내 authService의 생성자가 생성되지 않음
> 🔖 **TO-BE**
> final을 추가해 requiredConstructor가 authService의 생성자를 생성하도록 변경
> ### 테스트
>
> - [X] 테스트 코드

fix: 사진 서비스 버그 수정
